---
DEFAULT:
- :bwa_ref: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/bwa_7_6_indexed/human_g1k_v37.fasta
  :gatk_ref: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/bwa_7_6_indexed/human_g1k_v37.fasta
  :snp_rod: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/dbsnp_137.b37.vcf
  :interval_file: /net/flotsam.nfs.ngs.omrf.in/ifs/groups/wren_lab/scratch/temp/refGene.bed
  :known_indels:
  - /Volumes/hts_core/Shared/gatk_resources/2.3/b37/1000G_phase1.indels.b37.vcf
  - /Volumes/hts_core/Shared/gatk_resources/2.3/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
  :recalibration_known_sites:
  - /Volumes/hts_core/Shared/gatk_resources/2.3/b37/dbsnp_137.b37.vcf
  - /Volumes/hts_core/Shared/gatk_resources/2.3/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
  :keep_unaligned: false
  :quality_type: Standard
  :opts:
    :skip_btangs: true
    :skip_gvcf: false
    :skip_indel_realign: false
    :reduce_reads: false
  :vqsr_snp:
    :variant_recalibrator_opts:
      :maxGaussians: 6
      :mode: SNP
    :apply_recalibration_opts:
      :mode: SNP
      :ts_filter_level: 99.5
    :training_sets:
    - :name: hapmap
      :type: VCF
      :path: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/hapmap_3.3.b37.vcf
      :params: known=false,training=true,truth=true,prior=15.0
    - :name: omni
      :type: VCF
      :path: /Volumes/hts_core/Shared/gatk_resources/b37/1000G_omni2.5.b37.sites.vcf.gz
      :params: known=false,training=true,truth=false,prior=12.0
    - :name: dbsnp
      :type: VCF
      :path: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/dbsnp_137.b37.vcf
      :params: known=true,training=false,truth=false,prior=6.0
    :annotations:
    - MQRankSum
    - ReadPosRankSum
    - FS
    - DP
    - QD
  :vqsr_indel:
    :variant_recalibrator_opts:
      :maxGaussians: 4
      :mode: INDEL
      :stdThreshold: 10.0
    :apply_recalibration_opts:
      :mode: INDEL
      :ts_filter_level: 99.0
    :training_sets:
    - :name: mills
      :type: VCF
      :path: /Volumes/hts_core/Shared/gatk_resources/2.3/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
      :params: known=true,training=true,truth=true,prior=12.0
    :annotations:
    - MQRankSum
    - ReadPosRankSum
    - FS
    - DP
test: 
- :run: "001"
  :inputs: 
  - /net/flotsam.nfs.ngs.omrf.in/ifs/groups/wren_lab/scratch/temp/ERR034546_1.filt.fastq
  - /net/flotsam.nfs.ngs.omrf.in/ifs/groups/wren_lab/scratch/temp/ERR034546_2.filt.fastq
  :is_paired: true
  :lane: "1"